import dotenv from 'dotenv';
dotenv.config();

export const IMMUNIZATION_SERVER_DEFAULT_FHIR_URL = process.env.IMMUNIZATION_SERVER_DEFAULT_FHIR_URL || 'http://localhost:8080/fhir';
export const IMMUNIZATION_SERVER_TEFCA_QHIN_DEFAULT_FHIR_URL = process.env.IMMUNIZATION_SERVER_TEFCA_QHIN_DEFAULT_FHIR_URL || 'http://localhost:8081/fhir';
export const IMMUNIZATION_SERVER_LOCAL_HAPI_SERVER_URL = process.env.IMMUNIZATION_SERVER_TEFCA_QHIN_DEFAULT_FHIR_URL || 'http://localhost:8096/fhir';


export const IMMUNIZATION_SERVER_MONGODB_HOST = process.env.IMMUNIZATION_SERVER_MONGODB_HOST || 'localhost';
export const IMMUNIZATION_SERVER_MONGODB_PORT = process.env.IMMUNIZATION_SERVER_MONGODB_PORT || '27017';
export const IMMUNIZATION_SERVER_MONGODB_DATABASE = process.env.IMMUNIZATION_SERVER_MONGODB_DATABASE || 'immunization-dashboard';
export const IMMUNIZATION_SERVER_MONGODB_USERNAME = process.env.IMMUNIZATION_SERVER_MONGODB_USERNAME || '';
export const IMMUNIZATION_SERVER_MONGODB_PASSWORD = process.env.IMMUNIZATION_SERVER_MONGODB_PASSWORD || '';
export const IMMUNIZATION_SERVER_MONGODB_URI = process.env.IMMUNIZATION_SERVER_MONGODB_URI || 
  (IMMUNIZATION_SERVER_MONGODB_USERNAME && IMMUNIZATION_SERVER_MONGODB_PASSWORD 
    ? `mongodb://${IMMUNIZATION_SERVER_MONGODB_USERNAME}:${IMMUNIZATION_SERVER_MONGODB_PASSWORD}@${IMMUNIZATION_SERVER_MONGODB_HOST}:${IMMUNIZATION_SERVER_MONGODB_PORT}/${IMMUNIZATION_SERVER_MONGODB_DATABASE}`
    : `mongodb://${IMMUNIZATION_SERVER_MONGODB_HOST}:${IMMUNIZATION_SERVER_MONGODB_PORT}/${IMMUNIZATION_SERVER_MONGODB_DATABASE}`); 

    export const IMMUNIZATION_SERVER_URL = process.env.IMMUNIZATION_SERVER_URL || 'http://localhost:3000';
